package org.discord.commands;

import org.discord.interfaces.ExecuteArgs;
import org.discord.interfaces.ICommand;

public class CmdEloRip implements ICommand {

    @Override
    public void execute(ExecuteArgs event) {
        String[] allChamps = {"Aatrox", "Ahri", "Akali",
                "Akshan",
                "Alistar",
                "Amumu",
                "Anivia",
                "Annie",
                "Aphelios",
                "Ashe",
                "Aurelion Sol",
                "Azir",
                "Bard",
                "Bel'Veth",
                "Blitzcrank",
                "Brand",
                "Braum",
                "Caitlyn",
                "Camille",
                "Cassiopeia",
                "Cho'Gath",
                "Corki",
                "Darius",
                "Diana",
                "Dr. Mundo",
                "Draven",
                "Ekko",
                "Elise",
                "Evelynn",
                "Ezreal",
                "Fiddlesticks",
                "Fiora",
                "Fizz",
                "Galio",
                "Gangplank",
                "Garen",
                "Gnar",
                "Gragas",
                "Graves",
                "Gwen",
                "Hecarim",
                "Heimerdinger",
                "Illaoi",
                "Irelia",
                "Ivern",
                "Janna",
                "Jarvan IV",
                "Jax",
                "Jayce",
                "Jhin",
                "Jinx",
                "Kalista",
                "Karma",
                "Karthus",
                "Kassadin",
                "Katarina",
                "Kayle",
                "Kayn",
                "Kennen",
                "Kai'Sa",
                "Kha'Zix",
                "Kindred",
                "Kled",
                "Kog'Maw",
                "LeBlanc",
                "Lee Sin",
                "Leona",
                "Lissandra",
                "Lillia",
                "Lucian",
                "Lulu",
                "Lux",
                "Malphite",
                "Malzahar",
                "Maokai",
                "Master Yi",
                "Miss Fortune",
                "Mordekaiser",
                "Morgana",
                "Nami",
                "Nasus",
                "Nautilus",
                "Neeko",
                "Nidalee",
                "Nocturne",
                "Nunu",
                "Olaf",
                "Orianna",
                "Ornn",
                "Pantheon",
                "Poppy",
                "Pyke",
                "Quinn",
                "Qiyana",
                "Rammus",
                "Rek'Sai",
                "Renata Glasc",
                "Rakan",
                "Renekton",
                "Rengar",
                "Rell",
                "Riven",
                "Rumble",
                "Ryze",
                "Samira",
                "Senna",
                "Sett",
                "Sejuani",
                "Seraphine",
                "Shaco",
                "Shen",
                "Shyvana",
                "Singed",
                "Sion",
                "Sivir",
                "Skarner",
                "Sona",
                "Soraka",
                "Swain",
                "Sylas",
                "Syndra",
                "Tahm Kench",
                "Talon",
                "Taliyah",
                "Taric",
                "Teemo",
                "Thresh",
                "Tristana",
                "Trundle",
                "Tryndamere",
                "Twisted Fate",
                "Twitch",
                "Udyr",
                "Urgot",
                "Varus",
                "Vayne",
                "Veigar",
                "Vel'Koz",
                "Vex",
                "Vi",
                "Viego",
                "Viktor",
                "Vladimir",
                "Volibear",
                "Warwick",
                "Wukong",
                "Xayah",
                "Xerath",
                "Xin Zhao",
                "Yasuo",
                "Yorick",
                "Yone",
                "Yuumi",
                "Zac",
                "Zed",
                "Zeri",
                "Ziggs",
                "Zilean",
                "Zoe",
                "Zyra"};
        int random = (int) (Math.random()*allChamps.length);
        event.getTextChannel().sendMessage("Du fik: " + allChamps[random]).queue();
    }

    @Override
    public String getName() {
        return "EloRip";
    }

    @Override
    public String helpMessage() {
        return "Vælger en random champ";
    }

    @Override
    public boolean needOwner() {
        return false;
    }
}
